apiVersion: githubui.recipes/v0
id: default

target:
  owner: usememos
  repo: memos
  ref: ">=0.0.0"

runtime:
  type: compose
  composeFile: compose.yaml

ports:
  - name: ui
    service: memos
    protocol: http
    hostPort: 8108
    containerPort: 5230

ui:
  url: "http://localhost:8108"
  healthcheck:
    method: GET
    path: /
    expectStatus: 200

env:
  required: []
  optional: []

notes:
  setup: |
    No setup required. Open the UI and start writing memos.
  limitations: |
    This recipe is for local evaluation (Try locally).

