apiVersion: githubui.recipes/v0
id: default

target:
  owner: louislam
  repo: uptime-kuma
  ref: ">=1.0.0"

runtime:
  type: compose
  composeFile: compose.yaml

ports:
  - name: ui
    service: uptime-kuma
    protocol: http
    hostPort: 3001
    containerPort: 3001

ui:
  url: "http://localhost:3001"
  healthcheck:
    method: GET
    path: /
    expectStatus: 200

env:
  required: []
  optional: []

notes:
  setup: |
    On first run, open the UI and follow the onboarding flow to create an admin account.
  limitations: |
    This recipe is for local evaluation (Try locally). It does not cover production hardening or backup strategy.

