apiVersion: githubui.recipes/v0
id: default

target:
  owner: vrana
  repo: adminer
  ref: ">=0.0.0"

runtime:
  type: compose
  composeFile: compose.yaml

ports:
  - name: ui
    service: adminer
    protocol: http
    hostPort: 8101
    containerPort: 8080

ui:
  url: "http://localhost:8101"
  healthcheck:
    method: GET
    path: /
    expectStatus: 200

env:
  required: []
  optional: []

notes:
  setup: |
    No setup required. Open the UI and connect to a database if you have one.
  limitations: |
    This recipe is for local evaluation (Try locally). It does not provision a database.

