apiVersion: githubui.recipes/v0
id: default

target:
  owner: portainer
  repo: portainer
  ref: ">=2.0.0"

runtime:
  type: compose
  composeFile: compose.yaml

ports:
  - name: ui
    service: portainer
    protocol: http
    hostPort: 9443
    containerPort: 9443

ui:
  url: "https://localhost:9443"
  healthcheck:
    method: GET
    path: /
    expectStatus: 200

env:
  required: []
  optional: []

notes:
  setup: |
    On first run, open https://localhost:9443 in your browser and create the
    initial admin user, then connect Portainer to your local Docker environment.
    The default Portainer image exposes a HTTPS UI with a self-signed certificate.
  limitations: |
    This recipe is for local evaluation only. It does not configure certificate
    management, RBAC, TLS offload, or multi-node environments.

