apiVersion: githubui.recipes/v0
id: default

target:
  owner: benbusby
  repo: whoogle-search
  ref: ">=0.0.0"

runtime:
  type: compose
  composeFile: compose.yaml

ports:
  - name: ui
    service: whoogle
    protocol: http
    hostPort: 5001
    containerPort: 5000

ui:
  url: "http://localhost:5001"
  healthcheck:
    method: GET
    path: /
    expectStatus: 200

env:
  required: []
  optional: []

notes:
  setup: |
    No setup required. Open the UI and start searching.
  limitations: |
    This recipe is for local evaluation (Try locally).

