apiVersion: githubui.recipes/v0
id: default

target:
  owner: gitea
  repo: gitea
  ref: ">=0.0.0"

runtime:
  type: compose
  composeFile: compose.yaml

ports:
  - name: ui
    service: gitea
    protocol: http
    hostPort: 3003
    containerPort: 3000

ui:
  url: "http://localhost:3003"
  healthcheck:
    method: GET
    path: /
    expectStatus: 200

env:
  required: []
  optional: []

notes:
  setup: |
    Open the UI and follow the installation wizard (defaults are fine for a local try).
  limitations: |
    This recipe exposes only the HTTP UI port for quick evaluation.

