apiVersion: githubui.recipes/v0
id: default

target:
  owner: filebrowser
  repo: filebrowser
  ref: ">=2.0.0"

runtime:
  type: compose
  composeFile: compose.yaml

ports:
  - name: ui
    service: filebrowser
    protocol: http
    hostPort: 8080
    containerPort: 80

ui:
  url: "http://localhost:8080"
  healthcheck:
    method: GET
    path: /
    expectStatus: 200

env:
  required: []
  optional: []

notes:
  setup: |
    The default account is often admin/admin (follow the upstream docs). Change the password on first login.
  limitations: |
    This recipe is for local evaluation (Try locally). It mounts a local data volume to /srv for demo purposes.

